extends Node

# Release Management
signal SaveSourceFilterChanges
signal SelectedProjecItemUpdated

# Project Management
signal ToggleProjectItemSelection
signal ProjectSaved(project_id: String)
signal LoadOpenGodotButtons
signal HidingProjectItem
signal ReorderProjectItems
signal RemoveProject(project_id: String)

# Godot Version Management
signal NewGodotVersionAdded
signal GodotVersionItemClicked
signal GodotVersionManagerClosing
signal SaveGodotVersionSettingsFile
signal MoveVersionItemUp

# Settings
signal BackgroundColorChanged
signal BackgroundColorTemporarilyChanged
signal ClaudeCodeButtonEnabledChanged
signal ClaudeApiChatButtonEnabledChanged
signal ClaudeMonitorButtonEnabledChanged
signal ShowRunConsoleButtonChanged
signal ShowEditConsoleButtonChanged
