extends Node

# Release Management
signal SaveSourceFilterChanges
signal SelectedProjecItemUpdated

# Project Management
signal ToggleProjectItemSelection
signal ProjectSaved
signal LoadOpenGodotButtons
signal HidingProjectItem
signal ReorderProjectItems

# Godot Version Management
signal NewGodotVersionAdded
signal GodotVersionItemClicked
signal GodotVersionManagerClosing
signal SaveGodotVersionSettingsFile
signal MoveVersionItemUp

# Settings
signal BackgroundColorChanged
signal BackgroundColorTemporarilyChanged
